#!/bin/sh
# sadb: smart adb.
# A simple wrapper to enable smart devices selection
# Mon Feb 06 09:54:05 CST 2012: xiongchao
# 
# TODO:
# 1. better option handling, so the `-s' option should not be fixed in one
# place.
# 2. the grep here can be replace with `egrep' and thus enable a more
# standard-compliant pattern searching (though in the case of adb, this is not
# necessary.)

NAME=$(basename $0)
USAGE="${NAME} [-s <device-id-substr>] <adb commands>"

if [[ $1 != "-s" ]]; then
    # no device selection, apply adb directly
    echo "** WARNING: no device choice string. I will apply 'adb' directly."
    # echo "** usage: ${USAGE}"
    adb $*
    exit 0;
fi

# start device selction
SEARCH_STR=$2
GREP='grep -i'

SELECTION=$(adb devices | ${GREP} "${SEARCH_STR}" | awk '{print $1}')

if [[ $(echo $SELECTION | wc -w) > 1 ]]; then
    # ambiguity, output matches and exit
    echo "** AMBIGUITY: Multiple matches."
    adb devices | ${GREP} --color=auto ${SEARCH_STR}
    exit -1;
elif [[ $SELECTION = "" ]]; then
    # no match, output all and exit
    echo "** Empty: no matches for \"${SEARCH_STR}\""
    adb devices
    exit -2
else
    echo "** Single Match \"${SELECTION}\", applying commands..."
    # Q: how to refer to the rest of the arguments?
    adb -s ${SELECTION} $3 $4 $5 $6 $7 $8 $9
fi
